melink14/rikaikun

- rikaicontent.js
for example comment nodes inside text break him badly
I wonder if the project is still active
> make rikaikun not to break on not elements

- background.js
- manifest.json
- options.html
- options.js
- rikaicontent.js
Long awaited feature and annoyment reduction.
> Option for showing popup only when key is pressed and configurable delay to open popup.

- data.js
- rikaichan.js
Hello,
I made the small changes suggested by melink14 for JakeH's implementation of async dictionary loading ( https://github.com/melink14/rikaikun/pull/121)
Please let me know if it is OK, cheers!
> Asynchronous Dictionary Loading

- data.js
- rikaichan.js
Hi there. 
I've noticed that rikaikun takes a bit of time to become responsive after enabling. On my machine, it would take an average of 1500ms to completely load all dictionaries. 
To help reduce this, I've updated the dictionary initialization to use async calls and Promises to reduce the load time to around 800ms. 
Please review and let me know what you think.
> Async dictionary loading

- options.html
- options.js
- rikaicontent.js
Support setting a default popup location on new page loads (https://github.com/melink14/rikaikun/issues/84)
> Support setting a default popup location on new page loads

- .github/ISSUE_TEMPLATE/bug_report.md
These are the default templates github recommended with some small edits for rikaikun.
> Add bug report and feature request templates

- .github/workflows/node.js.yml
Changed name to ESLint since that's all we're running and made it only run when JS changes are pushed/requested.
> Update nodejs action to run less and have a better name

- extension/background.html
- extension/css/options.css
- extension/css/popup-black.css
- extension/css/popup-blue.css
- extension/css/popup-lightblue.css
- extension/css/popup-yellow.css
- extension/options.html
- package.json
Formatting and fixes was done by expanding the scope of prettier formatter to include HTML and CSS. A few additional CSS lint errors were fixed (reported by vscode).
package.json was updated to be more extensible with separate commands for the base programs that are then combined for the final lint and fix commands.
> Update package.json and fix formatting issues in HTML and CSS files.

- .github/workflows/node.js.yml
Also rename to Lint from ESLint since it includes prettier check as well.
> Update lint workflow to run on all changes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/dependabot.yml
- .github/workflows/node.js.yml
- .prettierrc.js
- CODE_OF_CONDUCT.md
- package.json
Practical result is that MD and YML files are now formatted and other files.
Additionally includes files with non standards file extensions.
Updated package.json and then ran `npm run fix` for the other changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/226)
>  style: Configure prettier to run on more filetypes and format them.

- .eslintrc.json
- extension/background.ts
- extension/data.ts
- extension/options.html
- extension/rikaichan.ts
- extension/rikaicontent.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/227)
> style: Replace all tabs with spaces and ban tabs.

- .github/dependabot.yml
Matches the standard https://www.conventionalcommits.org/en/v1.0.0/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/235)
> chore: Prefix dep update commits with 'chore'.

- .github/dependabot.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/239)
> chore: Include (deps) scope in dep update commit messages.

- .github/workflows/codeql-analysis.yml
Generated by clicking "enable code scanning" on the "Security" tab of the repo.
- Removed the master restriction on push/pull_request trigger.
- Removed the logic to skip merge commit since we only use squash and/or rebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/256)
> chore: Create CodeQL security scanning workflow

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/260)
> chore: Make the 0.8.0 heading in CHANGELOG.md the same size as the others.

- extension/background.ts
- extension/data.ts
- extension/options.html
- extension/rikaichan.ts
- extension/rikaicontent.ts
In some cases, code comments were replaced with clearer prose comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/269)
> style: Remove commented code from rikaikun.

- extension/manifest.json
> fix: Change manifest.json description to be more descriptive.

- .github/mergify.yml
- Change work-in-progress label to WIP
- Add 'Changes requested' label to allow approval with unresolved comments
- Exclude dependabot in main rule instead of using extra rule since all matching rules run so previous setup did nothing to protect dependabot.
> chore: Update mergify config and document

- README.md
- Chrome web store users badge now links to chrome web store
- license badge links to license file
> docs(readme): Make all badges the same style (flat) and add relevant links for users/license badges.

- extension/background.ts
- extension/rikaichan.ts
> fix: Migrate `onSelectionChanged` to `onActivated`

- extension/background.html
- extension/background.ts
- extension/data.ts
- extension/options.ts
- extension/rikaichan.ts
- extension/texttospeech.ts
- package-lock.json
- package.json
- tsconfig.json
- webpack.config.ts
- Updates webpack config to actually compile typescript files. Previously, the regex meant they were just copied direct.
- Had to switch to a new loader that actually let me ignore errors.
- Wrap business logic files as classes and export a singleton instance of them.
- Update properties and methods to be declared correctly for class syntax.
- Fix some undeclared variables that were fatal errors.
- Manually add expected globals to `window` so that options page can access them.
> refactor: Rewrite background scripts as classes and modules.

- .eslintrc.json
- extension/data.ts
- extension/rikaichan.ts
- extension/rikaicontent.ts
- Creates proper types and interfaces for various dictionary data.
- Simplies dictionary loading so that types are consistent and readable.
Contributes to #230.
> refactor(data): Fixes compiler warnings in data.js

- extension/data.ts
- extension/rikaichan.ts
- `rename variable` is scope specific it turns out.
> refactor(background): Change `initialConfig` -> `config` in all remaining places

- .eslintrc.json
- extension/rikaicontent.ts
- utils/update-db.ts
Enables any checks that could be fixed with small, mechanical improvements to the code base.
> refactor(fix-lint): Turn on and fix simple lint checks

- .eslintrc.json
- extension/background.ts
- extension/configuration.ts
- extension/data.ts
- extension/rikaichan.ts
- extension/rikaicontent.ts
- extension/texttospeech.ts
- utils/update-db.ts
- Most changes can mechanically be changed to the proper operator
- Some null checks were ambiguously comparing against undefined and
needed to be fixed.
> refactor(fix-lint): Enable eqeqeq check and fix errors

- .eslintrc.json
- extension/configuration.ts
- extension/data.ts
- extension/rikaichan.ts
- extension/rikaicontent.ts
> refactor(fix-lint): Add curly lint check that always requires curly braces and apply fixes

- .eslintrc.json
- extension/background.ts
- extension/rikaichan.ts
- extension/rikaicontent.ts
- Where readable, removed declaration
- Otherwise, added braces around case
> refactor(fix-lint): Enable and fix no-case-declaration violations

- .husky/commit-msg
- commitlint.config.js
- package-lock.json
- package.json
Also updates eslint config to not run Typescript checks on js files.
> chore: Add husky precommit hook for ensuring compliant commit messages

- CONTRIBUTING.md
4 space indent was used to preformat non-code blocks instead.
> docs(contributing): Ensures a single top level heading and removes code fences around preformatted non-code text

- CONTRIBUTING.md
- Visual regression tests
- Code coverage
- No more manual override checking
- chore -> build
> docs(contributing): Update contributing guide with new dev practices

- extension/css/popup.css
!important is no longer needed now that rikaikun is isolated from outside world.
> refactor(css): Remove unneeded `!important` and dead code from CSS

- .devcontainer/library-scripts/README.md
- .devcontainer/library-scripts/common-debian.sh
- .devcontainer/library-scripts/meta.env
- .devcontainer/library-scripts/node-debian.sh
This is required for building the image to work.
> build: Add library-scripts folder to .devcontainers

- .github/mergify.yml
This will allow me to self merge PRs without waiting for checks manually in order to use the override button.
> build: Allow mergify to approve my reviews

- .github/workflows/lint-pr-title-body.yml
- package-lock.json
- package.json
This is required now that I allow mergify to push merge commits to Dependabot PRs. The goal is to be lenient with Dependabot PRs in general, so really the PR author is what we need.
> ci(lint-pr-title): Use `github.event.pull_request.user.login` to detect Dependabot PRs

- CONTRIBUTING.md
Also, add a note that some validation runs on push in case people are surprised at how slow it is.
> docs: Note that we now have screenshot tests and fix typos

- extension/rikaicontent.ts
- tsconfig.json
- Add noUnusedLocals property mentioned in this issue: https://github.com/melink14/rikaikun/issues/1280
- Remove unused `dictCount` property detected by added flag.
Other useful tsconfig flags can be handled in subsequent pull requests
> build(tsconfig): Add noUnusedLocals to tsconfig.json

- extension/rikaichan.ts
Fixes #2154 
Saved the value to a variable (tabId) before checking explicitly if it was undefined and changed loop structure for cleaner code
> refactor: Remove non-null assertion from inlineDisable

- package.json
This is the first version that officially supports import.meta.dirname which is used in the new eslint.config.js file.
Merging this will unblock https://github.com/melink14/rikaikun/pull/2479
> build(package): Make required node version >=20.11.0
