melink14/rikaikun

- rikaicontent.js
https://github.com/melink14/rikaikun/issues/130
When rikaikun was disabled the `mousedown` event listener never got removed
because of a misspelled event name, therefore resulting in a following
error when clicking somewhere on a page:
```
Uncaught TypeError: Cannot set property 'oldCaret' of undefined
at Object._onMouseDown (chrome-extension://jipdnfibhldikgcjhfnomkfpcebammhp/rikaicontent.js:405)
at onMouseDown (chrome-extension://jipdnfibhldikgcjhfnomkfpcebammhp/rikaicontent.js:392)
```
> Fix mousedown event name

- data.js
- options.html
- rikaichan.js
- rikaicontent.js
A rikaikun user hovers over a japanese phrase. If a given phrase has more than 7 definitions, only the first 7 can be viewed, and all of the others are unable to be viewed.
This PR allows the definitions window to be scrollable forwards and backwards when there are too many definitions to be displayed. This allows all definitions to be viewed.
Rikaikun uses the ellipsis '...' to inform the user there are more definitions than can be displayed. When this is the case, the 'J' and 'K' keys can be used to scroll through the definitions forwards and backwards respectively (with loopback both ways).
- ellipsis on head and tail of definition window helps inform the user where they are. (first, middle, last)
When I approached this codebase, the max number of display-able definitions was …
> Add scroll support for many definitions

- .eslintrc.json
- .prettierrc.js
- extension/background.ts
- extension/options.ts
- extension/texttospeech.ts
- package-lock.json
- package.json
- utils/update-db.ts
Update eslint config to prefer `@returns` over `@return` to match formatter.
This required mirroring some unrelated `valid-jsdoc` config due to configs not being merged.
Use two newlines to force linebreak.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/217)
> style: Add prettier plugin that formats JSDoc comments and run it.

- .github/workflows/node.js.yml
Since a successful build is also something that can be automatically checked, let's do it.
Also made some small changes:
1. Make action run on all branches since otherwise stacked PRs don't get checks.
2. Don't run on Node 10.x since it's not active anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/melink14/rikaikun/238)
> chore: Update lint check to also build

- extension/manifest.json
As per https://developer.chrome.com/extensions/tabs the permission
is only needed if accessing sensitive tab information like URL or title.
rikaikun only needs chrome.tabs for sending messages which works fine.
TESTED: Manually tested core behavior.
Fixes #152
> fix: Remove unneeded tabs permission from manifest.

- extension/background.ts
I changed the logic that checks whether or not initial options values exist and whether or not they are true, to only check for whether or not they exist already. This way, if a false value for a checkbox is not mistaken for a missing setting value.
Solves issue https://github.com/melink14/rikaikun/issues/346.
--I attempted to rebase these changes as I initially committed without running the linter and I wanted to follow the "one commit per merge req" rule, however this was not recorded by Github.
> fix: Falsy setting values now correctly initialize.

- extension/manifest.json
Documented here: https://developer.chrome.com/docs/extensions/mv3/content_scripts/ but that page doesn't mention srcdoc. Essentially srcdoc is a way to inject html into an iframe and as such it doesn't have a `src` attribute. In this case, chrome treats the `src` attribute as `about:blank` which means without this option these types of frames won't have rikaikun injected into them.
This stackoverflow is a great overview and also implies that the documentation used to be better:
https://stackoverflow.com/questions/41408936/can-anyone-explain-that-what-is-the-use-of-match-about-blank-in-chrome-extensi
Inspired by https://github.com/birtles/rikaichamp/commit/946b3aad9ee000103e214a2e02ad1a9a08228ba4
Fixes #410
> fix: Update manifest.json to allow rikaikun to work in srcdoc iframes.

- .github/workflows/codeql-analysis.yml
For now, restricted paths to .js, .ts, .html, and .json.
Fixes #398
> ci: Make codeql only run on pushes to main branch and only on relevant pull requests.

- .github/workflows/codeql-analysis.yml
Github can't differentiate between skipped and failed.
> ci: Remove path restritions for codeql since it is a required check

- .github/workflows/resolve-comments.yml
- .github/workflows/update-pr-status.yml
Due to new security measures updating the status explicitly won't work from forks so we need to use workflow run as per: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
This can't be tested before merging so it may change later.
> ci: Add explicit step to report comment status to PR.

- webpack.config.ts
- A recent update to webpack now includes the `.` as part of the `[ext]` template making this change required to avoid background..html files in `dist/`
See https://github.com/webpack-contrib/copy-webpack-plugin/issues/574
Fixes #453
> chore(build): Remove extraneous `.` from webpack copy targets

- .eslintrc.json
- extension/data.ts
- extension/rikaichan.ts
BOM markers were breaking chrome unpacked extension loading because webpack never adds BOM markers by default.
Fixes #455
TESTED=Built and packaged in chrome with no problems.
> chore(build): Encode all files consistently as UTF-8 and add linter rule to enforce it.

- extension/background.ts
For some reason, chrome restores the previous badge state on restart causing inconsistency with actual rikaikun state.
TESTED=Loaded unpacked extension and used chrome://restart to ensure badge text reset.
Fixes #82
> fix: Reset badge text to empty on extension startup

- extension/rikaicontent.ts
This was added as part of hardening Data types but ended up causing a JS bug in some cases.
Fixes #495
> refactor(types): Moves declaration of `e` variable out of switch case

- extension/manifest.json
Required in order to easily publish to Edge with no errors.
> fix(manifest): Remove explicit reference to chrome in the short description

- .eslintrc.json
- extension/rikaicontent.ts
- extension/texttospeech.ts
- tsconfig.json
- Fix type issues without changing logic in rikaicontent.ts
-  Later, need to fix loose types and linter ignores.
- Fix minor issue in texttospeech.ts since it was the only one left.
- Disable unbound-method check in options LitElement since it's not lit aware and should be generally safe.
Fixes #230
> refactor(rikaicontent): Fix compilation errors in rikaicontent.ts

- extension/background.ts
- extension/docs-html-fallback.ts
- extension/manifest.json
- extension/test/background_test.ts
- extension/test/docs-html-fallback_test.ts
- snowpack.config.js
Google Docs new canvas mode hides all text/dom from rikaikun and thus for rikaikun to work Google has provided a workaround.
Fixes #593
> feat: Force Google Docs to use HTML mode instead of canvas mode

- codecov.yml
- Ignore tests directory for coverage
- Require 100% diff coverage
- Don't post coverage PR comments when there's no coverage change.
> ci(coverage): Adds codecov configuration

- snowpack.config.js
Chrome web store removes all 'hidden' folders when packaging extensions which it defines as folders/file with a leading `.`.
See https://bugs.chromium.org/p/chromium/issues/detail?id=23004
Fixes #607
> fix(build): Renames `.snowpack` metapath to `snowpack`

- extension/manifest.json
This should make Chrome Web Store highlight that the extension is enabled for offline use.
Fixes #429
> feat: Set `offline_enabled` to true in extension manifest

- extension/css/popup.css
Avoids inheriting veritcal text styles from host page when they're overly broad.
Long term, shadow dom should help, and we should also make a popup position that works well for vertical text.
Fixes #613
> feat(popup): Explicilty sets rikaikun to horizontal writing mode

- .github/workflows/presubmit.yml
- .husky/pre-push
- .prettierignore
- package.json
- Create a version which generates coverage data for CI and one that doesn't for pre-push hook.
- Fix husky install by adding `prepare` script
- Unify ignore files to use .gitignore after noticing failures with presubmit script
- Rename generic presubmit workflow to presubmit.
> ci: Create presubmit script and run during ci and pre-push

- .eslintrc.json
- extension/test/background_test.ts
- extension/test/docs-html-fallback_test.ts
- extension/test/rikaicontent_test.ts
Arrow functions always bind `this`, but mocha exposes testing data on a custom `this`. The mocha spefic lint rule ensures that arrow functions are used everywhere else except mocha tests.
See https://mochajs.org/#arrow-functions
> test: Ensures mocha callbacks are using non arrow functions

- package.json
- snowpack.config.js
- web-test-runner.config.mjs
- Coverage log spam errors are fixed by explicitly setting sourcemaps to be inline.
- Inline source maps appears to increase latency so increase default timeout to 5s.
- Sometimes SpecReporter is given test results that are incomplete so guards are added to make sure it doesn't throw errors.
- Later, we should incorporate DefaultReporter's top level error reporting. Until then,I've enabled both reporters to make sure we get all the test results.
- The `snowpack` meta directory is now properly excluded from the coverage report.
- Fixes the `npm test` script to be only include the `test` directory.
> test: Fixes coverage logspam and SpecReporter undef errors

- .github/workflows/presubmit.yml
- .github/workflows/release.yml
- .github/workflows/update-dicts.yml
- extension/test/background_test.ts
- package-lock.json
Changes:
- Update local npm to v8
- Delete `node_modules` and `package-lock.json` and run `npm i` with no preinstall
- Fix bad type usage in background_test.ts due to fixed types being pulled in with new lock file.
- Update all workflows to use Node 16 which uses npm 8 as well.
> chore(build): Update build to work with npm v8

- .github/mergify.yml
This change has been made by @melink14 from https://mergify.com config editor.
> ci(mergify): Migrate from strict merge to mergify queue action and from `commit_message` to `commit_message_template`

- package.json
The version field is updated in package-lock.json as well and until now it's only been updated in the next commit as an unrelated change.
> chore(release): Add package-lock.json as an asset to commit during release

- extension/manifest.json
Previous implementation (bb9b254) of this functionality breaks due to no manifest change.
This one is marked feat since the previous attempt was marked 'fix' accidentally.
Fixes #865
> feat: Enables Google docs annotate canvas in manifest

- commitlint.config.cjs
Since commitlint doesn't properly detect footers and max line lengths are an antipattern, this change will reduce false positive noise for no cost.
> chore(commitlint): Remove max line length for footer

- README.md
We stopped using it awhile ago.
> docs(readme): Remove GTS badge from README

- .github/dependabot.yml
chore is too generic and ecosystem is moving to more specific types.
> ci(dependabot): Update dependabot to use build and ci type instead of chore

- extension/rikaicontent.ts
- extension/test/rikaicontent_test.ts
Previously, it was copying no styles and thus often would produce an inaccurate duplicate of the real text.
Fixes #672
> fix: Emulate text affecting properties of input/textarea elements when creating fake

- .github/workflows/update-dicts.yml
Saves time and prevents flaky environment from preventing dictionary update PR.
> ci(update-dicts): Don't install git hooks when updating dictionaries

- .github/workflows/release.yml
Some presubmit tests fail in the absence of Japanese fonts and I'd prefer the tests still run since the release script pushes directly to the repo.
> ci(release): Install Japanese fonts before running release script

- extension/rikaicontent.ts
- extension/test/rikaicontent_test.ts
I found in offline mode I the cached Google Docs query selector was always false due to executing before page loaded. I now query the selector on every `mousemove` which seems fast enough. An improvement would be to memoize a function or perhaps add a on Dom loaded callback.
I also removed the check for if the target was `svg` or `rect` since there's at least one counter example to that assumption. For now let's avoid premature optimization.
I also had to update the tests to not overwrite the Google Docs class since it now needs to be present at each execution.
Fixes #897
Fixes #881
> fix(ui): Make Google Doc Canvas checks more lenient

- .github/dependabot.yml
- .github/mergify.yml
- .github/workflows/auto-approve-deps.yml
Uses dependabot/fetch-metadata to validate and approve PR and mergify to do final merge. Mergify doesn't support `first-commit` for queues which may be required due to merge commits. Instead, limit Dependabot to 1 open PR at a time and have Mergify merge them when ready. This avoids extra rebasing that happens when PRs are submitted one by one. Mergify will only attempt to merge when PRs are approved, have a single commit, and are caught up with main.
> ci(deps): Auto approve and merge Dependabot PRs

- .github/workflows/lint-pr-title-body.yml
Skipped jobs don't count for branch protection so this change will make the skipped commitlint job marked as passing, unblocking merging.
> ci(commitlint): Add a no-op passing commitlint job for dependabot

- .devcontainer/Dockerfile
- .devcontainer/base.Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- extension/test/background_test.ts
- Create a devcontainer.json for Codespaces.
- Unignore and add lint/formatting related vscode settings.json file.
- Also increases timeout of background_test tests due them often timing out in Codespaces.
> build: Add shareable dev environment configuration

- package-lock.json
- package.json
- Ran `npm audit fix`
- Used overrides to set `chrome-webstore-upload` at 1.0.0 to fix vulnerable `got`. Setting `got` directly led to errors
- Used overrides to set `glob-parent` to non-vulnerable version.
> build(deps): Remove vulnerable dependencies

- package-lock.json
- package.json
Due to ESM migration, this version of chrome-store-upload is not compatible with the chrome semantic release package.
> build: Remove override to chrome-store-upload 1.0.0

- README.md
- Updates mergify to a working badge endpoint
- Switches to dynamic all contributors badge and removes comments which broke formatting
- Adds new semantic release badge.
- Table of contents was re-generated with link to installing on Edge. (Was missed in previous updates)
> docs(readme): Update and fix badges plus re-generate table of contents

- extension/rikaicontent.ts
- extension/test/rikaicontent_test.ts
> fix: Remove fake div if returning early because `caretRangeFromPoint` is null

- package.json
This is mainly to comply with the standard readme spec.
> docs: Update description of rikaikun.package.json file

- .github/dependabot.yml
This will allow frequent dep updates while ideally reducing the number of spurious rebases by using Mergify's queue system.
Requried after https://github.com/dependabot/dependabot-core/issues/5234 killed the one PR at a time strategy.
> ci(deps): Update dependabot configuration to allow simultaneous open PRs but to not auto rebase them

- .github/mergify.yml
New attempt at efficient Dependabot merges now that https://github.com/dependabot/dependabot-core/issues/5234 was fixed in a way that doesn't work.
Will allow Mergify to keep PRs up to date but will ask Dependabot to rebase if conflicts.
This change has been made by @melink14 from Mergify config editor.
> ci(Mergify): Update mergify configuration to use merge queue on Dependabot

- .github/mergify.yml
Dependabot can't rebase PRs that have been edited and conflicts only occur when Mergify done it's own update.
> ci(mergify): Tell Dependabot to recreate PRs when there's a conflict

- extension/rikaicontent.ts
- extension/test/data_test.ts
- extension/test/rikaicontent_test.ts
The previous logic required the text box to be in a `<form>` element which is not often true.
A follow up to this should be to also handle other cases like `content: editable`. I'm not sure how that works now though so maybe it's fine.
Also, update the timeout for data_test.ts since it wasn't long enough to complete on the normal Github Codespace.
> fix(rikaicontent): Properly check for text areas and input elements when deciding to save cursor information on mousedown

- .github/mergify.yml
Originally, `recreate` was used in case the Dependabot PR had already had a merge commit pushed to it since `rebase` doesn't work on modified PRs. I had assumed that all conflicts would have at least 1 commit but it seems like conflict state happens before a commit is made (I guess a commit can't be finalized if there's a conflict)
In this case, rebase should work in almost all cases since each PR should get at most one merge commit when it's at the head of the queue. In special cases, where humans interrupt the queue there could be a problem but that is probably enough of an edge case to ignore.
> ci(mergify): When there is a conflict, have dependabot rebase instead of recreate

- .github/workflows/presubmit.yml
- Migrates to new `set-output` syntax to avoid deprecation warning.
- Marks `fetch: false` when adding commits for significant speed up.
- Excludes /screenshots directory when commiting lint fixes. This avoid inadvertantly committing failed screenshot metadata when visual regression tests fail. (Requiring a manual revert)
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See https://github.com/EndBug/add-and-commit/issues/386
> ci(presubmit): Fixes several quality of life issues in presubmit workflow

- .github/workflows/release.yml
semantic-release no longer supports < node 18 but given their aggressive node policy it's less work to just always use latest lts node version which is guranteed to work.
> ci: Update release workflow to use latest lts node version

- package-lock.json
- package.json
Installing the latest version makes updating stylelint impossible due to new peer dependency.
Later, we'll remove this package once stylelint is updated.
> build(deps): Unbump stylelint-config-prettier to 9.04

- .github/workflows/presubmit.yml
This might not be secure but should confirm if this allows commiting to PRs from forks.
> ci: Make presubmit workflow use pull_request_target

- web-test-runner.config.js
The current hardcoded path `/usr/bin/google-chrome` doesn't exist in dev environments like Mac OS making it hard to run tests locally. This change keeps the default but allows developers to override that with the path of their choosing.
> build(test-runner): Allow setting `executablePath` via an environment variable

- extension/data.ts
This pull request removes 2 unused functions in the data.ts file: `fileReadArray` and `makeHtmlForRuby`.
Feel free to close this pull request if we're planning on using these functions in the future.
If you use code search, you can see they're unused - so they can be safely removed:
- https://github.com/search?q=repo%3Amelink14%2Frikaikun%20fileReadArray&type=code
- https://github.com/search?q=repo%3Amelink14%2Frikaikun+makeHtmlForRuby&type=code
> refactor: Delete unused functions fileReadArray and makeHtmlForRuby

- extension/data.ts
- extension/test/data_test.ts
The goal of this pull request is to give variables in `makeText` more descriptive names so that the code is easier to understand. Some variables were also put into a more local scope so that they're easier to follow.
This pull request does not change the functionality of `makeText` - the copy-to-clipboard feature works exactly how it did before this pull request.
I tried to make this pull request have a small code diff so that it's easier to review. I plan on making more changes to `makeText` in subsequent pull requests which will make it even easier to understand.
Changes I plan on making in subsequent pull requests:
- Restructure the `kanjiInfoLabelList` array so that it's an array of objects - so its type might change to something like `{ kanjiInfoCode: string; kanjiInfoName: string …
> refactor(makeText): Rename variables, move variables to local scope

- extension/test/data_test.ts
Renaming the `makeText` test return values to `text` so that the reader focuses on the assertion line rather than the name of the variable returned from `makeText`.
This pull request only renames test variables - it doesn't change the behavior of any of the tests.
> test(makeText): Rename test variables

- extension/data.ts
The goal of this pull request is to simplify the `makeText` function by changing the kanji info labels type definition.
Changes:
- Change `kanjiInfoLabelList` type to `{ code: string; kanjiInfoLabel: string }[]`
- Use a for-of loop to iterate over `kanjiInfoLabelList`
- Replace `&amp;` with `&` so that code in `makeText` doesn't need to have code that does that
- `kanjiInfoLabelList` was [only used in `makeText`](https://github.com/search?q=repo%3Amelink14%2Frikaikun%20kanjiInfoLabelList&type=code) so this change is safe to make
- Rename `kanjiInfoLabelList` to `KANJI_INFO_LABELS`
- Make `KANJI_INFO_LABELS` private and static and readonly
This pull request doesn't change the behavior of `makeText` or the copy-to-clipboard feature - it only refactors `makeText` to be more simple.
> refactor(makeText): Make kanji info labels an array of objects

- extension/data/kanji.dat
- utils/update-db.ts
> fix(dict): Make update-db script resilient to multiple spaces separating kanji entry fields

- .husky/commit-msg
- .husky/pre-push
This is required since husky 9.1.1.
See typicode/husky#1474
> fix(tooling): Remove deprecated lines from husky hooks

- .github/workflows/lint-pr-title-body.yml
- .github/workflows/presubmit.yml
- .github/workflows/update-dicts.yml
Also, removes the requirement to `check-latest` for presubmit since even old versions of npm support override now.
> ci: Update node steps in all workflows to use an LTS node version

- extension/background.html
- extension/background.ts
- extension/clipboard.ts
- extension/data.ts
- extension/manifest.json
- extension/offscreen-setup.ts
- extension/offscreen.html
- extension/offscreen.ts
- extension/rikaichan.ts
- extension/rikaicontent.ts
- extension/test/background_test.ts
- extension/test/chrome_stubs.ts
- extension/test/data_test.ts
- extension/test/e2e_visual_test.ts
- package-lock.json
- package.json
- tsconfig.json
- Update manifest
- Switch to newer APIs
- Patch chrome stub with new APIs for testing
- Move clipboard and audio functionality into offscreen page (requires Chrome 109)
- rikaikun now remembers enabled/on state between startups; required due to ephemeral nature of new scripts.
BREAKING CHANGE: MV3 with offscreen pages requires at least Chrome 109 which is the new minimum version.
Fixes https://github.com/melink14/rikaikun/issues/187
Fixes https://github.com/melink14/rikaikun/issues/65
> feat!: Migrate to MV3

- extension/manifest.json
Chrome supports json comments but semantic-release-chrome does not; preventing the release of chrome.
The comment is replaced with a "//" json key.
> fix(manifest): Remove comment from manifest.json

- CHANGELOG.md
This was caused by the release failing partway through and the changelog logic just appending again when it was re-ran.
Probably it would have been better to rollback the release commit but forgot about this case.
> chore(changelog): Remove duplicate 3.0.0 entry in changelog

- extension/manifest.json
The * scheme only matches http and https so file URLs were being excluded.
> fix: Allow popup.css to be accessed from all URLs

- extension/docs-annotate-canvas.ts
- extension/manifest.json
- extension/test/docs-annotate-canvas_test.ts
- extension/test/test-augments.d.ts
New CSP changes means we can no longer inject a script into the MAIN world from the ISOLATED world.
Instead, we use the new `world` key to inject a simple script directly into the MAIN world.
One caveat of this is that we can no longer read the extension ID dynamically (as it's not available in MAIN world) so instead we hardcode it into the script as it extremely stable.
Fixes #2175
> fix(google-docs): Set docs_annotate_canvas property in a MV3 compliant manner

- .github/mergify.yml
- Rename `method` to `merge_method`
- Move merge settings to queue_rules (this required making a new queue to separate dependabot from non-dependabot.
This change has been made by @melink14 from the Mergify config editor.
> ci(mergify): Update configuration to avoid deprecation notices

- extension/rikaicontent.ts
It seems some bug was fixed in the background, since if it was a dependency change it would have caused a failure then.
> refactor: Remove unnecessary lint disable

- extension/test/e2e_visual_test.ts
- package-lock.json
- package.json
- patches/@web+test-runner-visual-regression+0.9.0.patch
- Don't use intersection observer in the test code, instead just poll.
- Patch visual-regression to focus tab before taking a screenshot.
See https://github.com/modernweb-dev/web/issues/2849 for additional details.
> test(visual): Fix e2e tests in new headless mode

- package-lock.json
- package.json
lit-analyzer was updated sometime last year and chokidar I'm not sure but removing and running npm audit doesn't list any new vulnerabilites.
Fixes #1101
> build(deps): Remove overrides now that they are no longer needed

- .vscode/launch.json
Without this, a cold start of vscode can't find sourcemaps for breakpoints.
> build(debugging): Don't limit resolution of source map locations

- eslint.config.js
- extension/background.ts
- extension/options.ts
- extension/test/background_test.ts
- extension/test/chrome_stubs.ts
- extension/test/data_test.ts
- extension/test/e2e_visual_test.ts
- extension/test/parse-word-dict-entry_test.ts
- extension/test/rikaicontent_test.ts
- package-lock.json
- package.json
- utils/update-db.ts
- vite.config.ts
- web-test-runner.config.js
The old sorter was working fine but just recently it crashed during linting due to reliance once deprecated eslint methods.
> refactor(formatting): Replace archived buggy import sorter with simple-import-sorter

- .prettierrc.js
This ends up causing parameter comments to be capitalized which we don't want.
> build(lint): Disable comment capitalization in prettier

- .prettierrc.js
Reverts melink14/rikaikun#2340
It turns out it only triggers for jsdoc style `/**` comments and I had mistakenly used one for my inline comment which caused the problem. Reverting the change since my reason doesn't apply and it might be useful.
> Revert "build(lint): Disable comment capitalization in prettier"

- package.json
This is the next LTS version that definitely supports import.meta.dirname. The previous attempt at this failed incorrectly pinned to the backport and thus didn't work.
Unblocks https://github.com/melink14/rikaikun/pull/2479
> build(package): Upgrade node version to >=22.0.0

- .github/workflows/presubmit.yml
Since the failed directory won't exist `ls` will always fail to list it's contents making it pure noise.
> build(ci): Don't print an error when there are no failed screenshots during presubmit

- extension/data.ts
The loadNames method and its underlying fileRead method (which used deprecated XMLHttpRequest) have been removed from the RcxDict class.
The name dictionary data (nameDict and nameIndex) is already initialized at startup using the fetch API within the init() method. The call to loadNames in wordSearch was therefore redundant as the data would always be present.
This change simplifies your codebase by removing unused methods and deprecated API usage, and makes nameDict and nameIndex non-nullable properties.
Fixes #2153
> refactor: Remove loadNames and fileRead methods
